### ISSUE TITLE
No Wildcard/Workflow/Archive Support?

### ISSUE THREAD

**Issue by BuildBackBuehler** [cdb-boop/ComfyUI-Model-Manager#1]
Would be quite nice to be able to download whatever from Civit. But I appreciate all the improvements you made to the OG ComfyUI-Model-Mgr! You really brought it up a notch as far as I'm concerned. 

I can't say I have as much time as I'd like to really mess around with SD these days, so this is just based off of 1 particular instance

https://civitai.com/models/138026?modelVersionId=251846

Vogon Guide to Beasts of the Galaxy [Wildcards]

I'd say automatic previews would be nice, but I think that's unfortunately on my end. I had previously looked into the CMM and to my surprise they had 'em. I have a feeling this issue may be related to my Workflow Manager failing to load (on account of GBDM/dbm gnu db failing to exist/be created). 

Honestly, other than that you've made it pretty perfect. If the other fella doesn't get on your merges in a reasonable amount of time you might as well consider just uploading your fork on Manager. Wouldn't be the first! But maybe OP could just add you into their instance as an admin/team member for future seamlessness. 

Cheers!

Edit: Whoops. Spoke too soon 😳😂. Seems I had luck with a LoRA! Time to see what else (will try another wildcard, too)

Edit2: Hm, donno if there's an option to fetch for updates, that'd be awesome! It looks like that may be outside the scope of work rn because it seems that downloads do not include some sorta metadata...unless that's "app-side" aka in the custom node. Civit-Downloader would include these. Many moons ago I was working on a Model Manager and figured I'd just take from them and potentially accidental Civit-DL integration

[DD-made-of-clay-XL-v2.civit.full.txt](https://github.com/cdb-boop/ComfyUI-Model-Manager/files/15017203/DD-made-of-clay-XL-v2.civit.full.txt)
[DD-made-of-clay-XL-v2.civit.txt](https://github.com/cdb-boop/ComfyUI-Model-Manager/files/15017204/DD-made-of-clay-XL-v2.civit.txt)

**Comment by cdb-boop** [comment]
Thanks for the praise! I was just looking for that A1111 model card viewer experience in ComfyUI.

> I can't say I have as much time as I'd like to really mess around with SD these days, so this is just based off of 1 particular instance
> 
> https://civitai.com/models/138026?modelVersionId=251846
> 
> Vogon Guide to Beasts of the Galaxy [Wildcards]

Actually, I made wildcards/workflows/zips inaccessible by design. I thought it was out-of-scope for a "model manager". Maybe if someone had a well thought-out and backward-compatible/standardized design, I could consider adding it.

**Comment by BuildBackBuehler** [comment]
> Thanks for the praise! I was just looking for that A1111 model card viewer experience in ComfyUI.
> 
> > I can't say I have as much time as I'd like to really mess around with SD these days, so this is just based off of 1 particular instance
> > https://civitai.com/models/138026?modelVersionId=251846
> > Vogon Guide to Beasts of the Galaxy [Wildcards]
> 
> Actually, I made wildcards/workflows/zips inaccessible by design. I thought it was out-of-scope for a "model manager". Maybe if someone had a well thought-out and backward-compatible/standardized design, I could consider adding it.

Ah makes sense. I remember having looked at the A1111 CivitAI model manager when I was looking into making a manager here. It did seem confangled so I imagine that would not be the design you're looking for hahaha. At some point I'll probably dabble with the Edit2 stuff and see how much more I can round out those features, at least. Hopefully I stumble upon something translatable to this

**Comment by BuildBackBuehler** [comment]
Okay, finally got some time in with ComfyUI, especially if not entirely with this 😂😭. 

i. Wish I had seen the download description as notes option yesterday, perhaps better under the "Download" tab. Can quickly opt for good descriptions and just as quickly opt out when its spam/useless. Preferably shown/editable

ii. Models Tab: filters + comparisons. Poor man's filter would just to be able to have subdirectories shown in the model folder selection. It'd be cool to have both at our fingertips. Comparisons I'm thinking would require the user to 1. select the models 2. click button that brings up popup window, or need a new menu tab to hop over to. 3. Horizontal/Vertical Table View of your chosen models' thumbnails, notes. Just brainstorming, may be if possible -- esp. with filter/tags would provide a table. Then you'd have a reason to have this convoluted idea I think. You can quickly narrow down models that fit your needs, then compare and choose off a glance (tag table w/ "HQ @ low steps", "1024x1024 only", "DPMPP", "Euler A")

iii. Hover over a model for description popup (blocks 60% of the image, black bg, white text)

Just the ideas that came to mind while using CMM. (I'll attempt to add some of these things in when I find time!)

**Comment by cdb-boop** [comment]
Suggestion and any contributions are welcome. Here's some of my thoughts.

> i. Wish I had seen the download description as notes option yesterday, perhaps better under the "Download" tab. Can quickly opt for good descriptions and just as quickly opt out when its spam/useless. Preferably shown/editable

Yeah, I debated putting it in the Settings or Download Tab. I guess you're right, it should go in the Download Tab.

I guess I was trying to avoid the work of then needing to show the Civitai model descriptions in Summary/Details html tags. Hiccups are that each Civitai model has one overall model description, and each model version has it's own description, and the info has HTML tags that I crudely strip out when saving as a note.

> Poor man's filter would just to be able to have subdirectories shown in the model folder selection.

I'm not sure I follow. Is what you're suggesting functionally different than this:

![model_search_subdirectory_suggestions](https://github.com/cdb-boop/ComfyUI-Model-Manager/assets/80225746/b951bf5b-cb55-4372-aac5-a31483da6ae8)

> Comparisons I'm thinking would require the user to 1. select the models 2. click button that brings up popup window, or need a new menu tab to hop over to. 3. Horizontal/Vertical Table View of your chosen models' thumbnails, notes. Just brainstorming, may be if possible -- esp. with filter/tags would provide a table. Then you'd have a reason to have this convoluted idea I think. You can quickly narrow down models that fit your needs, then compare and choose off a glance (tag table w/ "HQ @ low steps", "1024x1024 only", "DPMPP", "Euler A")

The obstacles are,

1. The model manager itself is an HTML modal (not my idea), and so I was hesitant to change it or have multiple modals simultaneously for model info. It may not be hard to change, but I was trying to avoid it in case something broke.

2. The reason I don't have search filters/tags like SD version, sampler or whatever, is that when searching for embedded model preview images in safetensors files, there was a noticeable delay. In fact, one of the primary drivers for me to stop using A1111 was that startup and models refreshing was unacceptably slow. That's why the model manager currently only reads model info one model at a time. Now, the results and 'file last-modified' timestamps could be cached to speed it up.

> iii. Hover over a model for description popup (blocks 60% of the image, black bg, white text)

This sounds fine, as long as it doesn't noticeably impact load times and doesn't interfere with dragging a model's preview image onto the node graph.
